# 池化层
池化是一种典型的空间降维方法，通过控制输出形状，将输入和输出之间的空间维度降低。同时可以帮助减少参数数量，并提高计算效率。还可以帮助模型得到更好的数据抽象表达。

卷积对于数据的偏移以及位置有很高的要求。为了避免这种要求带来的限制，使用`池化`方法作用在卷积输出上，对有一定偏移的数据有很好的效果。

池化没有可学习的参数，具有填充和步幅两个超参数，作用在多通道，对每个通道做输出，不会融合多输入通道，得到输出通道数等于输入通道数。

池化层分为最大池化层和平均池化层。

`最大池化层`：输出窗口内最强的模式信号。

`平均池化层`：将最大池化层中的“最大”操作替换为“平均”。


In [4]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size # 池化滑动窗口的高和宽
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max': # 最大池化层
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg': # 平均池化层
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

## 验证二维最大池化层的输出

In [5]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## 验证二维平均池化层的输出

In [7]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## 填充和步幅

In [8]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

## PyTorch中步幅和池化大小相同默认

In [9]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

### 手动修改`padding`和`stride`

In [11]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [12]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 多通道

In [17]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10.],
          [11., 12., 13., 

### 输出的通道数和输入相同

In [18]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 9., 11.],
          [17., 19.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [1