# 求导

In [2]:
import torch

In [5]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

在计算y关于$x$的导数的时候，需要一个地方存储梯度。

In [6]:
x.requires_grad_(True) # 等价 x = torch.arange(4.0, requires_grad = True)
x.grad # 默认是None

In [7]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算`y`关于`x`每个分量的梯度。

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

默认情况下pytorch可以累积梯度。

In [10]:
x.grad.zero_() # 清零
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

在深度学习课程中很少会涉及微分矩阵的计算。
某些计算可以移动到记录的计算图之外。

In [11]:
x.grad.zero_()
y = x*x
u = y.detach() # u是一个常数，不是一个关于x的函数
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [12]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

即使构建函数的过程需要使用条件、循环或者任意函数调用这种Python控制流的方法，仍然可以计算得到变量的梯度。

In [16]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(),requires_grad = True)
d = f(a)
d.backward()
a.grad == d/a

tensor(True)